# Skabelon i DP-Next-projektet {#sec-skabelon}

## Formål

- Kort beskrivelse af formålet sop'en/undersøgelsen

## Baggrund

- Relevant baggrundsinformation, hvis det er nødvendigt

## Anvendelsesområde

- Hvem udfører undersøgelsen
- Hvilke deltagere der skal undersøges, og hvornår i projektet undersøgelsen udføres
- Eventuelle krav til faste, timing eller hvile
- Eventuelle krav til kvalifikationer/oplæring af personalet, der skal udføre undersøgelsen

## Udstyr og forberedelse

- Udstyr og materiale der skal bruges til undersøgelsen
- Forberedelse af udstyr, lokale og deltagere forud for undersøgelsen

## Sikkerhed

- Relevante sikkerhedsforanstaltninger
- Kontraindikationer
- Indikationer på, at undersøgelsen bør afbrydes

## Data

- Beskriv kort, hvilken type data undersøgelsen genererer, hvis det er relevant

## Instruktioner

- Eventuelle standardiserede instruktioner til deltageren

## Procedure

- Beskriv undersøgelsen trin for trin, og supplér med billeder hvis det er relevant
- Opdel undersøgelsen i forskellige faser, hvis det er nødvendigt:
- Forberedelse
- Trin 1
- Trin 2
- Udførelse
- Trin 1
- Trin 2
- Afslutning
- Trin 1
- Trin 2

## Dokumentation og kvalitetskontrol

- Angiv relevante kontroller og dokumentation under og efter undersøgelsen

## Afvigelser og fejl

- Forventede resultater (hvordan ser et gyldigt resultat/gyldige målinger ud)
- Handlinger, hvis der opstår fejl eller afvigelser
- Relevante kontaktpersoner

## Referencer

- Relaterede SOP'er, protokoller eller litteratur

## Versionshistorik

| Version | Dato       | Udarbejdet af    | Godkendt af |
|---------|------------|------------------|-------------|
| 1       | 30.09.2026 | Mikkel Steentoft |             |
